### PR TITLE
Inappropriate use of `&thinsp;` in french localization

### PR DESCRIPTION
**Pull request by maxdup**
Hi :)

Problem:
The french localisation uses `&thinsp;` in ways that would be typographically appropriate for web pages.
However, html elements such as `&nbsp;`, `&thinsp;`, etc... are usually not supported in html emails.
Needless to say, they are absolutely not supported in plaintext emails.

This leads to visible/readable `&thinsp;` codes in emails.

My solution:
I've removed `&thinsp;` instances from the loc strings intended for email templates.

Alternative solution (which I wouldn't necessarily recommend):
Implement a way to strip `&nbsp;`, `&thinsp;`, etc... from emails within Flask-security's MailUtil.

### CODE REVIEW

**Comment by jwag956** [comment]
Obviously these errors aren't from your PR - I'll look into what's going on.

**Review by sr-verde — APPROVED** [review]
Looks good.

**Review by jwag956 — APPROVED** [review]
Thanks

**Comment by maxdup** [comment]
Thanks for merging :) keep up the good work <3

**Pull request merged**
