### PR TITLE
Upgrade bionic (18.04) to focal (20.04)

### PR DESCRIPTION
**Pull request by fuhrysteve**

### CODE REVIEW

**Comment by jwag956** [comment]
I'll follow this later today - I have had some issue with Travis lately - besides taking forever. If this one fails - I'll flush all the caches and see if that helps.

**Comment by fuhrysteve** [comment]
Yeah I think they are pushing folks to move towards travis-ci.com for faster builds. I'll keep poking at this, seems to be something weird going on with some pre-commit hook

**Comment by jwag956** [comment]
Note that I pushed a change that updated all our pre-commits - I think that will fix this - if you rebase and push - I think it will work.
Thanks

**Comment by jwag956** [comment]
I am going to move away from travis over to github actions - travis is getting too slow and unreliable.

**Pull request closed without merging**
