### PR TITLE
Uniformity in Templates

### PR DESCRIPTION
**Pull request by ademaro**
I propose to make a single style in the templates, so that it would be more convenient for developers to work. If you have any comments or suggestions on how to do better - let's chat. I'm ready to make everything beautiful.

As an option, we can try to connect and configure the linter for templates for automation.
https://pypi.org/project/djlint/

What do you think?

### CODE REVIEW

**Comment by jwag956** [comment]
This is great - so did you user djlint to change these (or should I ask - will they now pads djlint?)

Adding this as a pre-commit would be ideal - do you have time to try to add that?

**Comment by ademaro** [comment]
I started using djlint in my projects, but there are not many settings yet. I can prepare basic settings for the current project, let's give it a try. The basic points it will be able to find or even fix, but so far this tool is far from perfect. If someone uses something more advanced, I am ready to help with configuration and debugging.

Should I implement djlint in this pool-request?

And one more thing: after changing templates, I should probably make new po/mo files for localizations (babel)?

**Comment by jwag956** [comment]
Let’s start with the PR as is - it’s a great startIf you want to work on a precommit - go for itDon’t worry about babel stuff - I do that just before a releaseSent from my iPhoneOn Jan 29, 2023, at 11:33 AM, Ademaro ***@***.***> wrote:﻿
I started using djlint in my projects, but there are not many settings yet. I can prepare basic settings for the current project, let's give it a try. The basic points it will be able to find or even fix, but so far this tool is far from perfect. If someone uses something more advanced, I am ready to help with configuration and debugging.
Should I implement djlint in this pool-request?
And one more thing: after changing templates, I should probably make new po/mo files for localizations (babel)?

**Comment by jwag956** [comment]
This error isn't your fault - I'll work on this and then rebase your PR.

**Review by jwag956 — DISMISSED** [review]
Love it ... thanks.

**Comment by jwag956** [comment]
I've fixed the sqlalchemy issue - could you rebase and it should pass now.

Thanks.

**Review by jwag956 — APPROVED** [review]

**Pull request merged**
