### PR TITLE
Use get_id instead of id

### PR DESCRIPTION
**Pull request by rrrealman**
#312

### CODE REVIEW

**Comment by jwag956** [comment]
I have been having problems with travis hooks - make sure the build passes:
https://travis-ci.org/github/jwag956/flask-security

My guess is this might be trickier that it seems - and it will cause existing tokens to stop working. Also note that recently - we changed get_id() to return a alternative id (the fs_uniqifier) - which may not cause an issue but something to be aware of.

**Comment by rrrealman** [comment]
Thank you for rapid feed back. I recently checked out branch R3.4.1 and ran `pytest -x --disable-pytest-warnings` and it failed with this
```
____________ test_token_change ____

app = <Flask 'conftest'>, client_nc = <FlaskClient <Flask 'conftest'>>

    def test_token_change(app, client_nc):
        # Verify can change password using token auth only
        login_response = json_authenticate(client_nc)
        token = login_response.json["response"]["user"]["authentication_token"]
    
        data = dict(
            password="password",
            new_password="new strong password",
            new_password_confirm="new strong password",
        )
        response = client_nc.post(
            "/change?include_auth_token=1",
            json=data,
            headers={"Content-Type": "application/json", "Authentication-Token": token},
        )
>       assert response.status_code == 200
E       assert 401 == 200
E        +  where 401 = <Response streamed [401 UNAUTHORIZED]>.status_code

tests/test_changeable.py:204: AssertionError
```
Am I doing something wrong? I've installed all flask-security dependencies along with pytest and tox into the same virtual environment, if it matters.

**Comment by jwag956** [comment]
HMm - are you sure you don't have any of your get_id() changes in there? which I think could possibly cause this problem.
Travis is clean, and my local seems to work...

**Comment by rrrealman** [comment]
Sorry, it was my fault, I messed up flask-security and flask-security-too)

**Comment by jwag956** [comment]
@rrrealman please take a look at #339 - I am moving in a different direction - which I believe will solve your issue as well...

**Comment by jwag956** [comment]
#339 resolves this I believe in a different way - FS no longer references the PK of the UserModel.

**Pull request closed without merging**
