### PR TITLE
Support for latest Werkzeug and Flask and Flask-Login

### PR DESCRIPTION
**Pull request by jwag956**
flask-login changed where they store the current user - we used that (it was internal). It is now on 'g' which is part of the app context so for
a couple unit tests - wasn't getting popped (it used to be on the request context).

Following Flask guidelines - changed our get/set of request attributes (fs_authn_via) over to 'g' as well.

### CODE REVIEW

**Comment by dadiletta** [comment]
Since updating my dependencies, I'm getting the following error: 
```
(psycopg2.errors.InvalidTextRepresentation) invalid input syntax for integer: "5818f9aad20447b1b6a37c51f2c2xxxx"
LINE 3: WHERE "user".id = '5818f9aad20447b1b6a37c51f2c2xxxx'
```
Do I need to refactor my whole code to now support `user.id` as a string rather than an int?

**Comment by jwag956** [comment]
This has been an issue in the past due to psycopg2 being very particular about ‘types’. You don’ mention precisely what versions you went from/to - which would be useful. Flask-Security-Too since 4.0.0 hasn’t used user.id - it uses user_model.fs_uniquifier. Note that Flask-Security-Too UserMixin defines get_id() to return the fs_uniquifier, not user.id. Possibly you have over-ridden that?

Seeing your model would help, and any subclassing of  Flask-Login or Flask-Security would be useful.

**Comment by dadiletta** [comment]
> Seeing your model would help, and any subclassing of Flask-Login or Flask-Security would be useful.

I've posted additional details to this [Stackoverflow post](https://stackoverflow.com/questions/73238163/flask-login-trying-to-change-my-user-id-into-random-strings-instead-of-establish). Happy to provide any additional information.

**Comment by dadiletta** [comment]
So if Flask-Login uses `user_id = session.get("_user_id")` which gets the fs_uniquifier and not the ID... then following the thread, we take that inaccurate `user_id` Flask-Security's core to the datastore where I crash because the datastore is trying to look up with mismatched kwargs. 

I had considered rolling back Flask-Login or FS2, but that caused all sorts of new conflicts. I think the only solution is to take the absurd step to change all my user ID's to match the fs_uniquifier and change postgres's primary key to a new property. That way it can query for `user_id` using the FS2's uniquifier

**Comment by jwag956** [comment]
There must be some customization you are doing that I am not understanding
I assume that you have a column called fs_uniquifier in your user model - FS manages that and flask login stores that in the session

This should be transparent to your app??

**Comment by dadiletta** [comment]
The only customization to Flask-Security has been overwriting templates/emails. Here's the bulk of my User class. It seems that Flask-Login's `_load_user()` fetches session data mislabeled as the ID and then the datastore launches a query based on that data. 
```
# User class
class User(db.Model, UserMixin):
    """
    User object closely tied to UserStore from Flask-Security
    """
    id = db.Column(db.Integer, primary_key=True)
    # PROPS
    first_name = db.Column(db.String(155))
    last_name = db.Column(db.String(155))
    display_name = db.Column(db.String(255))
    image = db.Column(db.String(155))
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    fs_uniquifier = db.Column(db.String(255), unique=True, default=uuid_generator)
    """This property is required by Flask-Security-Too"""
    about_me = db.Column(db.Text())
    yog = db.Column(db.String(4))
    # TOGGLES
    active = db.Column(db.Boolean(), default=True)
    text_alerts = db.Column(db.Boolean(), default=False) 
    email_alerts = db.Column(db.Boolean(), default=True) 
    """total toggle on receiving emails"""
    hide_tooltips = db.Column(db.Boolean(), default=False) 
    # DATES
    dob = db.Column(db.DateTime())
    confirmed_at = db.Column(db.DateTime())
    last_seen = db.Column(db.DateTime(), default=None)
    # RELATIONSHIPS
    posts = db.relationship('Post', backref='user', lazy='dynamic')
    roles = db.relationship(
        'Role',
        secondary=roles_users,
        backref=db.backref('users', lazy='dynamic')
    )
```

**Pull request merged**
