### PR TITLE
added hy_AM translations

### PR DESCRIPTION
**Pull request by rudolfamirjanyan**
Added Armenian language translations.

### CODE REVIEW

**Comment by jwag956** [comment]
Thanks for doing this - please rebase and re-commit and that should restart the CI. Just so happened that on the same day another developer added some translations.

**Comment by rudolfamirjanyan** [comment]
> Thanks for doing this - please rebase and re-commit and that should restart the CI. Just so happened that on the same day another developer added some translations.

**Comment by rudolfamirjanyan** [comment]
Thank you Chris. I did another commit/push.

**Comment by jwag956** [comment]
Since there are conflicts - you actually need to merge (and deal with conflicts) and push again. On the PR page in github you should see 'This branch has conflicts that must be resolved' and button that says 'resolve conflicts' that lets you do it right in github or a link to 'command line' that shows you how to use git on your local machine.

Thanks!

**Comment by rudolfamirjanyan** [comment]
Thanks you for your help Chris,  I really appreciate it.

**Review by jwag956 — APPROVED** [review]

**Pull request merged**
