### PR TITLE
Don't disclose why login attempt was invalid (OWASP)

### PR DESCRIPTION
**Pull request by fuhrysteve**
OWASP rules seem to indicate that for an invalid login, you should provide a generic error message regardless of whether:

> The user ID or password was incorrect.
> The account does not exist.
> The account is locked or disabled.

For details, please see:
https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md#authentication-and-error-messages

Given the specified goals of this project to "Use OWASP to guide best practice and default configurations," it seems as though these defaults ought to be made generic.

Let me know if I missed anything!

### CODE REVIEW

**Comment by fuhrysteve** [comment]
I wonder if we should change the language to say "Invalid username or password, or the account has been disabled" for all three?

**Comment by jwag956** [comment]
So - further in that OWASP specification is:
"The problem with returning a generic error message for the user is a User Experience (UX) matter. A legitimate user might feel confused with the generic messages, thus making it hard for them to use the application, and might after several retries, leave the application because of its complexity. The decision to return a generic error message can be determined based on the criticality of the application and its data. For example, for critical applications, the team can decide that under the failure scenario, a user will always be redirected to the support page and a generic error message will be returned."

So I think maybe the best would be to support and offer both models - having messages and translations for either scenario and a config variable that easily switches between modes.
Thoughts?

**Comment by jwag956** [comment]
So I am not completely on board with this approach. It is quite confusing so have different message keys all have the same message - but more importantly - we will lose all our language translations if we do this.
As I am sure you are aware - it is already possible today to simply re-define the messages in your application.
I am not opposed to offering an easy way to configure which model an application wants - rather than forcing one group of the other to find all the appropriate messages and modifying them

**Comment by fuhrysteve** [comment]
@jwag956 understood - I'll close for now, as a way to make a flag like you're describing work doesn't seem easy to implement or understand well as a user.

**Pull request closed without merging**
