### PR TITLE
Fix for #483

### PR DESCRIPTION
**Pull request by kuba-lilz**
Changed core._request_loader so that api tokens generated with version 3.x are correctly consumed

### CODE REVIEW

**Review by jwag956 — APPROVED** [review]
Make sure you run pre-commit in order to fix things like the black error here. You can use tox or run pre-commit manually - it is documented in CONTRIBUTING.rst.

**Comment by jwag956** [comment]
@kuba-lilz - are you going to have some time to fix the black formatting issue and re-submit?

**Comment by PuchatekwSzortach** [comment]
@jwag956 (I'm replying from a different account)
I'll fix it by no later than first half of next week! (It's a series of holidays in my part of the world now, sorry!)

**Comment by jwag956** [comment]
No worries - and no rush - just checking in.

**Comment by kuba-lilz** [comment]
@jwag956
A noob question I guess, but... where is "pre-commit" script?
I read about it in CONTRIBUTING.rst, but couldn't find it, which is why I didn't run it on the first push.

I tried searching for it, but nothing came up
```bash
find . -type f -name "pre*"
./.git/hooks/pre-rebase.sample
./.git/hooks/pre-commit.sample
./.git/hooks/pre-receive.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/pre-push.sample
```

**Comment by jwag956** [comment]
As part of installing dev requirements pip -r requirements/dev.txt that should have installed pre-commit and that should be in your virtualenv bin.
You can also use tox which installs and runs it.

**Review by jwag956 — APPROVED** [review]
The black errors are due to a new version of black - I'll fix those.

**Pull request merged**
