### PR TITLE
Fix security vuln - QRcodes were available via GET on /qrcode - not p…

### PR DESCRIPTION
**Pull request by jwag956**
…rotected with CSRF tokens

Looking into how others do this (e.g. paypal) - the QRcode is embedded in the successful response to form POST.
So - /tf-qrcode and /us-qrcode endpoints have been completely removed.

A successful response to POST /tf-setup or /us-setup will contain the embedded QRcode in addition to the constituent parts: key, username, and issuer. This allows for manual authenticator app setup. In addition the JSON response to these POST calls also have that information.

Simpler, more secure - what's not to like.

closes: #418

### CODE REVIEW

**Comment by jwag956** [comment]
@baurt I would be interested in your thoughts on this - I think it is much simpler and more secure!

**Comment by baurt** [comment]
> @baurt I would be interested in your thoughts on this - I think it is much simpler and more secure!

Makes sense. It's a little unclear about the compatibility issues.  It would probably be better if it explicitly stated that these changes are breaking for two factor/unified sign in if there a custom template is used for the two_factor_setup endpoint (which I assume that most will have.)  That seems like it's the only breaking change, otherwise everything else makes sense.

**Comment by jwag956** [comment]
@baurt Thanks for your quick reply - yes - in the CHANGES section this is called out explicitly, and yes - that is the only breaking change in this PR (and the change is really just one line in the template).

**Comment by baurt** [comment]
@jwag956 Awesome.  I like it.  Makes more sense to have the QR code as an image in the response to a POST rather than it's own page as a GET too.  If it makes it more secure, that's a wonderful improvement.

**Review by baurt — APPROVED** [review]
LGTM.

**Pull request merged**
